import type { CategoryKey } from "./aqi";
import type { Claim, HardFailReason } from "./confidence";
import type { Compass } from "./geo";
import type { CheckKey, CheckStatus } from "./reportChecks";

export type PanelTab = "overview" | "city" | "news" | "insight" | "reports";

export type Lang = "en" | "hi";

const en = {
  wordmark: "Project Vayuchakra",
  enableSound: "Enable typing sound",
  soundOn: "Typing sound on",
  about: "About",
  close: "Close",
  langToggleLabel: "Switch language",
  locationOff: "Location off — showing Delhi. You can still tap the map.",
  nearYou: "NEAR YOU",
  selectedPoint: "SELECTED POINT",
  placeUnknown: "Unnamed place",
  loading: "Loading…",
  airUnavailable: "Air data is unavailable at this point right now.",
  hourlyScaleCaption: "Hourly PM2.5 on the India AQI scale",
  hourlyPm25: "Hourly PM2.5",
  srcGoogle: "Google Air Quality",
  srcCams: "CAMS via Open-Meteo · hourly",
  camsNote: "Global model, about 45 km grid. Not a street reading.",
  laterToday: (v: number, t: string) => `About ${v} µg/m³ around ${t} IST, from the same source.`,
  estimateLine: (v: number, model: string) =>
    `Spatial estimate ${v} µg/m³ · LightGBM ${model} · same-day reconstruction, not a forecast`,
  scaleGood: "Good",
  scaleSevere: "Severe",
  nearbyReports: "Nearby reports · 5 km",
  noNearbyReports: "No checked reports within 5 km.",
  reportWhatYouSee: "Report what you see",
  howNumberMade: "How this number is made",
  layerHeatmap: "Modelled PM2.5 field",
  layerStations: "Stations",
  heatmapLabel: "Modelled PM2.5 field · not a live sensor",
  stationsLabel: "Station areas · values from the air route, not CPCB live",
  stationArea: "station area · not CPCB live",
  zoomIn: "Zoom in",
  zoomOut: "Zoom out",
  bandLabel: { corroborated: "Checked", plausible: "Plausible", unverified: "Saved, not shown" } as Record<string, string>,
  yours: "Yours",
  rejectedLabel: "Not published",
  // Report flow
  back: "Back",
  reportTitle: "Report what you see",
  whatType: "What is it?",
  claim: {
    smoke: "Smoke or burning",
    dust: "Dust",
    traffic: "Traffic haze",
    construction: "Construction",
    unsure: "Not sure",
  } as Record<Claim, string>,
  note: "Note (optional)",
  notePlaceholder: "What do you see? Hindi or English.",
  photo: "Photo",
  takePhoto: "Take photo",
  chooseFile: "Choose file",
  photoTooBig: "That file is over 8 MB. Choose a smaller photo.",
  photoWrongType: "Use a JPEG, PNG, or WebP photo.",
  checkPhoto: "Check this photo",
  checking: (n: number) => `Checking the photo · attempt ${n} of 3`,
  attemptOf: (n: number) => `Attempt ${n} of 3`,
  tryAnother: "Choose another photo",
  done: "Done",
  pinLocked: "The report is tied to this pin. Go back to start one somewhere else.",
  networkError: "Something went wrong. Try again.",
  publishedCorroborated: "Published. It shows on the map as Checked.",
  publishedPlausible: "Published. It shows on the map as Plausible.",
  publishedUnverified: "Saved, not shown — confidence too low.",
  scoreTooLow: (n: number) =>
    `Evidence score ${n}/100 — below 60, so we need another photograph. This try still counts. Capture the source and a landmark, closer but without entering any hazard.`,
  verifiedLive: (model: string) => `Verified live using ${model}`,
  howAssessed: "How Gemini assessed this",
  scoreBreakdown: "Evidence score, calculated here — not invented by Gemini",
  weightQuality: "Image quality · 30%",
  weightEvent: "Visual-event match · 25%",
  weightLocation: "Location / time · 20%",
  weightSensor: "Satellite or sensor · 15%",
  weightReport: "Report consistency · 10%",
  contradictionsTitle: "Contradictions",
  combineLine: (best: number, bonus: number, penalty: number) =>
    `Best photo ${best}${bonus ? ` · +${bonus} for agreeing photos` : ""}${penalty ? ` · −${penalty} for contradictions` : ""}`,
  briefTitle: "Incident brief",
  briefHappened: "What probably happened",
  briefWhere: "Where",
  briefEvidence: "Evidence",
  briefExposed: "Exposed areas",
  briefAction: "Recommended action",
  briefUncertainty: "Uncertainty",
  confidenceLine: (n: number) => `Confidence ${n} / 100`,
  rejected: "We could not verify a photo in 3 tries. Nothing was published.",
  rateLimited: "You can file 5 reports a day from this browser.",
  reportsUnavailable: "Reports are not available right now.",
  hardFail: {
    quality: "That frame is hard to read. Step back and include the sky or the source.",
    stock: "This looks like a screenshot or a downloaded picture. Take a photo here.",
    indoor: "This looks indoors. Step outside and retake it.",
    place_conflict: "This photo does not look like the pin. Retake it at the place you selected.",
    exif_far: "The photo’s location is {km} km from the pin. Retake it here, or move the pin.",
    gemini_failed: "Our photo checker did not respond. This is a problem on our side, not with your photo. Try again.",
  } as Record<HardFailReason, string>,
  checkerBusy: "Our photo checker is at its usage limit right now. This is on our side, not your photo, and this try did not count. Wait a minute and try again.",
  refusedTitle: "Photo not accepted",
  checkerTitle: "Couldn’t check the photo",
  errorCode: (code: string) => `Error code: ${code}`,
  // Map panel
  basemapSatellite: "Satellite",
  basemapMap: "Map",
  layers: "Layers",
  layerAqi: "AQI heatmap",
  layerCpcb: "CPCB stations",
  layerFires: "Satellite fires",
  layerReports: "Citizen reports",
  heatSourceGoogle: "Heatmap: Google Air Quality, US AQI colours",
  heatSourceCams: "Heatmap: CAMS model via Open-Meteo, NCR only",
  stationsSource: "Stations: CPCB via data.gov.in, published index",
  stationsMissing: "Stations need a data.gov.in key",
  firesSource: "Fires: NASA FIRMS VIIRS, last 48 h",
  legendScale: "India AQI",
  stationPopup: (aqi: number | null, pollutant: string | null) =>
    aqi === null ? "No reading" : `CPCB index ${aqi}${pollutant ? ` · led by ${pollutant}` : ""}`,
  updated: (t: string) => `Updated ${t}`,
  // Card sections
  health: {
    good: "Minimal impact.",
    satisfactory: "Minor breathing discomfort for sensitive people.",
    moderate: "Breathing discomfort for people with asthma, lung or heart disease, children and older adults.",
    poor: "Breathing discomfort for most people on long exposure. Limit time outdoors.",
    very_poor: "Respiratory illness on long exposure. Avoid outdoor exercise; wear an N95 outside.",
    severe: "Affects healthy people too. Stay indoors, keep windows shut, and use a purifier if you can.",
  } as Record<CategoryKey, string>,
  pollutantsTitle: "Pollutants now",
  next24h: "Next 24 hours · PM2.5",
  now: "Now",
  weatherLine: (temp: number | null, compass: string | null, speed: number | null) =>
    [temp !== null ? `${temp}°C` : null, compass && speed !== null ? `Wind from ${compass}, ${speed} km/h` : null]
      .filter(Boolean)
      .join(" · "),
  nearestStation: "Nearest CPCB station",
  stationLine: (km: string, aqi: number | null, t: string | null) =>
    `${km} km away · index ${aqi ?? "—"}${t ? ` · ${t} IST` : ""}`,
  firesTitle: "Satellite fires, last 48 h",
  firesLine: (near: number, upwind: number) =>
    `${near} within 50 km · ${upwind} upwind within 400 km`,
  firesUpwindHint: "Upwind fires can carry smoke here.",
  insightTitle: "Why is the air like this?",
  insightBadge: "Gemini",
  insightLoading: "Reading the news, fires and wind…",
  insightUnavailable: "No explanation right now.",
  kidTitle: "Can you explain this like I'm a kid?",
  kidLangNote: "Always in English, in simple words.",
  insightConfidence: { low: "Low confidence", medium: "Medium confidence", high: "High confidence" } as Record<string, string>,
  newsTitle: (area: string) => `In the news · ${area}`,
  newsEmpty: "No recent air-quality news for this area.",
  newsMissing: "News needs a SerpApi key.",
  newsNearest: (area: string) => `No recent news for ${area}, so this is the nearest city.`,
  newsFailed: {
    bad_key: "The news service rejected our key.",
    out_of_searches: "The news service is out of searches for this month.",
    failed: "Could not load news right now.",
  } as Record<string, string>,
  agoMinutes: (n: number) => `${n} min ago`,
  agoHours: (n: number) => `${n} h ago`,
  agoDays: (n: number) => `${n} d ago`,
  // Panel tabs
  tabs: { overview: "Overview", city: "City", news: "News", insight: "AI report", reports: "Reports" } as Record<PanelTab, string>,
  expand: "Widen panel",
  collapse: "Narrow panel",
  seeAll: "See all",
  // Photo checks
  checksTitle: "What we checked",
  checkerSaw: "What the checker saw",
  checkLabel: {
    quality: "Image quality",
    outdoor: "Outdoor scene",
    authentic: "Real photo",
    claim_match: "Matches what was reported",
    smoke_visible: "Smoke or fire visible",
    place: "Fits the pinned place",
    exif: "Photo location",
    satellite_fire: "Satellite fire nearby",
  } as Record<CheckKey, string>,
  checkValue: (key: CheckKey, status: CheckStatus, value: string | number | null | undefined): string => {
    switch (key) {
      case "quality":
        return ({ good: "Sharp and clear", blurry: "Blurry", dark: "Too dark", too_close: "Too close", obstructed: "View blocked" } as Record<string, string>)[String(value)] ?? "";
      case "outdoor":
        return status === "pass" ? "Yes" : "Looks indoors";
      case "authentic":
        return status === "pass" ? "Looks like a real camera photo" : "Looks like a screenshot or downloaded image";
      case "claim_match":
        return `${value ?? 0}% fit`;
      case "smoke_visible":
        return status === "pass" ? "Yes" : "Not clearly visible";
      case "place":
        return status === "pass" ? (value ? `Cues: ${value}` : "Nothing conflicting") : String(value || "Looks like a different place");
      case "exif":
        return status === "info" ? "No GPS in the photo (that is fine)" : `${value} km from the pin`;
      case "satellite_fire":
        return status === "pass" ? `NASA saw a fire ${value} km away` : "No satellite fire within 15 km";
    }
  },
  visibleLabel: {
    smoke: "Smoke",
    dust: "Dust",
    haze: "Haze",
    open_burning: "Open burning",
    construction: "Construction",
    traffic: "Traffic",
    none: "Nothing notable",
    unclear: "Unclear",
  } as Record<string, string>,
  resultPublished: "Report published",
  resultRejected: "Report not published",
  // City tab
  cityTitle: (city: string) => `${city} · CPCB stations`,
  cityNoStations: "No CPCB station within 60 km of this point.",
  cityAvg: "City average",
  cityWorst: "Highest",
  cityBest: "Lowest",
  cityStations: (n: number, reporting: number) => `${reporting} of ${n} stations reporting`,
  cityCategories: "Stations by category",
  cityDominant: "Leading pollutant at stations",
  cityStationList: "All stations",
  cityIndexNote: "CPCB’s published index: the highest pollutant sub-index at each station.",
  cityFires: "Satellite fires, last 48 h",
  firesWithin: (km: number) => `within ${km} km`,
  firesUpwindLabel: "upwind, 400 km",
  cityReports: "Checked citizen reports within 15 km",
  reportsLast7: "last 7 days",
  reportsAll: "all time",
  // Insight tab
  insightEvidence: "What Gemini looked at",
  evReading: "Reading",
  evWind: "Wind",
  evTemp: "Temperature",
  evFires: "Fires (48 h)",
  evHeadlines: "Headlines",
  evBasis: (b: string) => `Measured at ${b}, shared by all of Delhi NCR`,
  evFiresValue: (near: number, up: number) => `${near} within 50 km · ${up} upwind`,
  causesTitle: "Likely causes",
  citedTitle: "Headlines it cited",
  insightMeta: (model: string, t: string) => `Written by ${model} at ${t} IST`,
  insightDisclaimer: "An AI summary of the evidence above. It can be wrong, and it never changes the number.",
  trendTitle: "PM2.5 trend it saw",
  // Reports tab
  feedTitle: "Reports within 10 km · last 30 days",
  feedNone: "No published reports here in the last 30 days.",
  feedPrivacy: "Photos and notes stay private. You see what was reported, when, and what our checker saw.",
  reportedAs: (claim: string) => `Reported: ${claim}`,
  confidenceShort: (n: number) => `${n}/100`,
  kmAway: (km: string) => `${km} km away`,
  // Context sentence
  compass: { n: "north", ne: "northeast", e: "east", se: "southeast", s: "south", sw: "southwest", w: "west", nw: "northwest" } as Record<Compass, string>,
  ctxReportsFire: (n: number, km: string, dir: string, h: number, compass: string, speed: number) =>
    `${n} checked ${n === 1 ? "report" : "reports"} within 5 km. A satellite hotspot was ${km} km ${dir} of here, ${h} h ago. Wind is from the ${compass} at ${speed} km/h, so nearby smoke can drift.`,
  ctxReports: (n: number, compass: string, speed: number) =>
    `${n} checked ${n === 1 ? "report" : "reports"} within 5 km. Wind is from the ${compass} at ${speed} km/h.`,
  ctxReportsNoWind: (n: number) => `${n} checked ${n === 1 ? "report" : "reports"} within 5 km.`,
  ctxFire: (km: string, h: number) =>
    `No checked reports within 5 km. A satellite hotspot was ${km} km away, ${h} h ago.`,
  ctxNothing: "No checked reports within 5 km. The number above is the hourly field at this point, not a street sensor.",
  // About
  aboutTitle: "About Project Vayuchakra",
  aboutIntro:
    "Project Vayuchakra is a live air map for Delhi NCR and nearby North India. Tap any point: you get the hourly air there, nearby CPCB stations, satellite fires upwind, local pollution news, and a Gemini reading of what is likely driving the air. People can also file a photo that is actually checked — not just uploaded.",
  aboutDisclaimer:
    "The big number is hourly PM2.5 on the India AQI scale, not CPCB’s official 24-hour index. Citizen photos are checked by Gemini and are not official readings. Where a layer is modelled, the map says so.",
  aboutMapTitle: "The map",
  aboutMap: [
    "Satellite imagery by default (Esri), or a light street map. You can toggle the AQI heatmap, CPCB stations, satellite fires and citizen reports.",
    "The coloured heatmap is Google Air Quality tiles (US AQI colours) when the Google key is set. Without it, NCR gets a coarser CAMS model grid coloured on the India AQI scale.",
    "Station dots are CPCB’s own published index from data.gov.in — the only official measured numbers on the site, about 600 of them. Hover for the reading; click to select that point.",
    "Glowing dots are NASA FIRMS VIIRS fire detections from the last 48 hours across Punjab, Haryana, Delhi and western Uttar Pradesh. The card counts fires within 50 km and upwind within 400 km, because smoke travels.",
  ],
  aboutLiveTitle: "What you see for a point",
  aboutLive: [
    "The header is tinted by category and shows health advice, temperature and wind, a six-pollutant grid (PM2.5, PM10, NO₂, O₃, CO, SO₂), and the next 24 hours of PM2.5 as a chart.",
    "The City tab lists CPCB stations in that city (or within 25 km), the city average, highest and lowest, which pollutant is leading, and fire and report counts.",
    "The News tab pulls Google News via SerpApi for pollution, AQI, smog and fire. Small places with no headlines show the nearest city instead.",
    "Widen the panel if you want those grids side by side. Everything stays on the same page.",
  ],
  aboutAiTitle: "What Gemini does",
  aboutAi: [
    "“Why is the air like this?” is a Gemini summary of only the evidence we already have: the reading, the 24-hour trend, wind, fire counts and numbered headlines. It names likely causes and cites headlines by number. It never changes the AQI number.",
    "“Can you explain this like I’m a kid?” is the same evidence in simple English, as if talking to an eight-year-old. No jargon, no invented fires.",
    "Photo reports are a live multimodal Gemini call. We send the photograph plus what you claimed, the pin, capture time, EXIF GPS, nearby AQI, wind and nearby satellite fires. Headlines are background only; Gemini is told to judge the photo, not the news.",
    "Gemini returns what the photo shows, quality, consistencies and contradictions. Vayuchakra then calculates the evidence score itself: 30% image quality, 25% visual-event match, 20% location/time, 15% satellite or sensor, 10% report consistency. Gemini does not invent that percentage.",
    "Below 60, it asks for a specific retake — closer, include a landmark, too dark — for up to three tries. The final score is the best photo, plus a bonus if the photos agree, minus a penalty for contradictions.",
    "After a photo is accepted, Gemini writes a short incident brief for officers: what probably happened, where, the evidence, nearby areas, a recommended action, and what is still uncertain. Other people see that story on the Reports tab, never the image.",
  ],
  howTitle: "How this number is made",
  howBody: [
    "We take the latest hourly PM2.5 at the point from Google Air Quality. If Google has no PM2.5 value, we use the CAMS global model via Open-Meteo, which is about 45 km coarse. The line under the number always names the source.",
    "We place that hourly value on the CPCB 2014 India AQI breakpoints for PM2.5. CPCB’s official index uses a 24-hour average and whichever pollutant is worst at a station, so this is not the official CPCB AQI — it reacts faster and can be higher or lower.",
    "If a same-day LightGBM spatial estimate exists for the point, it is shown as a separate line. It is a reconstruction, not a forecast. The 24-hour bars are the same source’s hourly forecast, converted the same way.",
  ],
  sourcesTitle: "Data sources",
  sources: [
    "Google Air Quality API — current and hourly forecast PM2.5 and other pollutants",
    "Google Air Quality heatmap tiles — the coloured AQI layer (US AQI colours)",
    "CAMS global forecast via Open-Meteo — fallback PM2.5",
    "Open-Meteo Forecast API — wind and temperature",
    "CPCB real-time station index via data.gov.in — station markers and the City tab",
    "NASA FIRMS, VIIRS NOAA-20 (NOAA-21 retry) — satellite fire hotspots across Punjab, Haryana, Delhi and western UP",
    "SerpApi Google News — local pollution, AQI, smog and fire headlines",
    "Gemini — photo checks, the “Why is the air like this?” summary, the kid explanation, and the incident brief",
    "Google Geocoding, then OpenStreetMap Nominatim — place names",
    "Imagery © Esri, Maxar, Earthstar Geographics · Map © OpenStreetMap contributors © CARTO",
  ],
  photosTitle: "Photo reports",
  photosBody:
    "Each report gets three photo tries. A checker failure on our side (quota, missing model) does not use up a try. Only corroborated and plausible reports appear on the map. Photos and your note stay private; the public feed shows what was reported, when, how far, what the checker saw, and the brief.",
  aboutPrivacyTitle: "Keys and privacy",
  aboutPrivacy:
    "Gemini, Google, FIRMS, data.gov.in, SerpApi and the database service role stay on the server. The browser never receives those keys. All report reads and writes go through Next.js routes with the service role; there are no open database policies for attempts or Gemini JSON.",
};

type Copy = typeof en;

const hi: Copy = {
  ...en,
  enableSound: "टाइपिंग की आवाज़ चालू करें",
  soundOn: "टाइपिंग की आवाज़ चालू है",
  about: "परिचय",
  close: "बंद करें",
  langToggleLabel: "भाषा बदलें",
  locationOff: "लोकेशन बंद है — दिल्ली दिखा रहे हैं। आप फिर भी नक्शे पर टैप कर सकते हैं।",
  nearYou: "आपके पास",
  selectedPoint: "चुनी गई जगह",
  placeUnknown: "अज्ञात जगह",
  loading: "लोड हो रहा है…",
  airUnavailable: "इस जगह का हवा का डेटा अभी उपलब्ध नहीं है।",
  hourlyScaleCaption: "प्रति घंटा PM2.5, भारत AQI पैमाने पर",
  hourlyPm25: "प्रति घंटा PM2.5",
  srcCams: "CAMS via Open-Meteo · प्रति घंटा",
  camsNote: "वैश्विक मॉडल, लगभग 45 किमी ग्रिड। यह सड़क का माप नहीं है।",
  laterToday: (v, t) => `लगभग ${v} µg/m³, ${t} IST के आसपास, इसी स्रोत से।`,
  estimateLine: (v, model) =>
    `स्थानिक अनुमान ${v} µg/m³ · LightGBM ${model} · उसी दिन का पुनर्निर्माण, पूर्वानुमान नहीं`,
  scaleGood: "अच्छा",
  scaleSevere: "गंभीर",
  nearbyReports: "पास की रिपोर्ट · 5 किमी",
  noNearbyReports: "5 किमी के भीतर कोई जाँची गई रिपोर्ट नहीं।",
  reportWhatYouSee: "जो दिख रहा है, बताएँ",
  howNumberMade: "यह संख्या कैसे बनती है",
  layerHeatmap: "मॉडल PM2.5 परत",
  layerStations: "स्टेशन",
  heatmapLabel: "मॉडल PM2.5 परत · लाइव सेंसर नहीं",
  stationsLabel: "स्टेशन क्षेत्र · मान हवा रूट से, CPCB लाइव नहीं",
  stationArea: "स्टेशन क्षेत्र · CPCB लाइव नहीं",
  zoomIn: "ज़ूम इन",
  zoomOut: "ज़ूम आउट",
  bandLabel: { corroborated: "जाँची गई", plausible: "संभावित", unverified: "सहेजी गई, दिखाई नहीं गई" },
  yours: "आपकी",
  rejectedLabel: "प्रकाशित नहीं",
  back: "वापस",
  reportTitle: "जो दिख रहा है, बताएँ",
  whatType: "यह क्या है?",
  claim: {
    smoke: "धुआँ या जलना",
    dust: "धूल",
    traffic: "ट्रैफ़िक धुंध",
    construction: "निर्माण",
    unsure: "पक्का नहीं",
  },
  note: "टिप्पणी (वैकल्पिक)",
  notePlaceholder: "आपको क्या दिख रहा है? हिंदी या अंग्रेज़ी में।",
  photo: "फ़ोटो",
  takePhoto: "फ़ोटो लें",
  chooseFile: "फ़ाइल चुनें",
  photoTooBig: "यह फ़ाइल 8 MB से बड़ी है। छोटी फ़ोटो चुनें।",
  photoWrongType: "JPEG, PNG या WebP फ़ोटो इस्तेमाल करें।",
  checkPhoto: "यह फ़ोटो जाँचें",
  checking: (n) => `फ़ोटो जाँची जा रही है · प्रयास ${n} / 3`,
  attemptOf: (n) => `प्रयास ${n} / 3`,
  tryAnother: "दूसरी फ़ोटो चुनें",
  done: "ठीक है",
  pinLocked: "यह रिपोर्ट इसी पिन से जुड़ी है। दूसरी जगह के लिए वापस जाएँ।",
  networkError: "कुछ गड़बड़ हुई। फिर से कोशिश करें।",
  publishedCorroborated: "प्रकाशित। नक्शे पर ‘जाँची गई’ के रूप में दिखेगी।",
  publishedPlausible: "प्रकाशित। नक्शे पर ‘संभावित’ के रूप में दिखेगी।",
  publishedUnverified: "सहेजी गई, दिखाई नहीं गई — भरोसा बहुत कम है।",
  scoreTooLow: (n) =>
    `सबूत स्कोर ${n}/100 — 60 से कम, इसलिए एक और फ़ोटो चाहिए। यह कोशिश गिनी गई। स्रोत और कोई पहचान वाला निशान लें, पास से लेकिन खतरे में घुसे बिना।`,
  verifiedLive: (model) => `${model} से लाइव जाँची गई`,
  howAssessed: "Gemini ने यह कैसे जाँचा",
  scoreBreakdown: "सबूत स्कोर, यहाँ गिना गया — Gemini ने नहीं बनाया",
  weightQuality: "फ़ोटो की गुणवत्ता · 30%",
  weightEvent: "दृश्य घटना से मेल · 25%",
  weightLocation: "जगह / समय · 20%",
  weightSensor: "सैटेलाइट या सेंसर · 15%",
  weightReport: "रिपोर्ट की संगति · 10%",
  contradictionsTitle: "विरोध",
  combineLine: (best, bonus, penalty) =>
    `सबसे अच्छी फ़ोटो ${best}${bonus ? ` · सहमत फ़ोटो के लिए +${bonus}` : ""}${penalty ? ` · विरोध के लिए −${penalty}` : ""}`,
  briefTitle: "घटना संक्षेप",
  briefHappened: "शायद क्या हुआ",
  briefWhere: "कहाँ",
  briefEvidence: "सबूत",
  briefExposed: "प्रभावित इलाके",
  briefAction: "सुझाया गया कदम",
  briefUncertainty: "अनिश्चितता",
  confidenceLine: (n) => `भरोसा ${n} / 100`,
  rejected: "3 प्रयासों में फ़ोटो की पुष्टि नहीं हो सकी। कुछ भी प्रकाशित नहीं हुआ।",
  rateLimited: "इस ब्राउज़र से आप एक दिन में 5 रिपोर्ट भेज सकते हैं।",
  reportsUnavailable: "रिपोर्ट अभी उपलब्ध नहीं हैं।",
  hardFail: {
    quality: "यह फ़्रेम साफ़ नहीं है। थोड़ा पीछे हटें और आसमान या स्रोत को शामिल करें।",
    stock: "यह स्क्रीनशॉट या डाउनलोड की गई तस्वीर लगती है। यहीं फ़ोटो लें।",
    indoor: "यह अंदर की फ़ोटो लगती है। बाहर जाकर दोबारा लें।",
    place_conflict: "यह फ़ोटो पिन वाली जगह की नहीं लगती। चुनी गई जगह पर दोबारा लें।",
    exif_far: "फ़ोटो की लोकेशन पिन से {km} किमी दूर है। यहीं दोबारा लें, या पिन हटाएँ।",
    gemini_failed: "हमारा फ़ोटो जाँचने वाला सिस्टम जवाब नहीं दे पाया। दिक्कत हमारी तरफ़ है, आपकी फ़ोटो में नहीं। फिर से कोशिश करें।",
  },
  checkerBusy: "हमारा फ़ोटो जाँचने वाला सिस्टम अभी अपनी सीमा पर है। दिक्कत हमारी तरफ़ है, आपकी फ़ोटो में नहीं, और यह कोशिश गिनी नहीं गई। एक मिनट रुककर फिर कोशिश करें।",
  refusedTitle: "फ़ोटो स्वीकार नहीं हुई",
  checkerTitle: "फ़ोटो जाँची नहीं जा सकी",
  errorCode: (code) => `त्रुटि कोड: ${code}`,
  basemapSatellite: "सैटेलाइट",
  basemapMap: "नक्शा",
  layers: "परतें",
  layerAqi: "AQI हीटमैप",
  layerCpcb: "CPCB स्टेशन",
  layerFires: "सैटेलाइट आग",
  layerReports: "नागरिक रिपोर्ट",
  heatSourceGoogle: "हीटमैप: Google Air Quality, US AQI रंग",
  heatSourceCams: "हीटमैप: CAMS मॉडल (Open-Meteo), केवल NCR",
  stationsSource: "स्टेशन: CPCB (data.gov.in), प्रकाशित सूचकांक",
  stationsMissing: "स्टेशनों के लिए data.gov.in की चाबी चाहिए",
  firesSource: "आग: NASA FIRMS VIIRS, पिछले 48 घंटे",
  legendScale: "भारत AQI",
  stationPopup: (aqi, pollutant) =>
    aqi === null ? "कोई माप नहीं" : `CPCB सूचकांक ${aqi}${pollutant ? ` · मुख्य: ${pollutant}` : ""}`,
  updated: (t) => `अपडेट ${t}`,
  health: {
    good: "न्यूनतम असर।",
    satisfactory: "संवेदनशील लोगों को साँस लेने में हल्की तकलीफ़।",
    moderate: "अस्थमा, फेफड़े या दिल की बीमारी वालों, बच्चों और बुज़ुर्गों को साँस लेने में तकलीफ़।",
    poor: "लंबे समय तक रहने पर ज़्यादातर लोगों को साँस में तकलीफ़। बाहर कम समय बिताएँ।",
    very_poor: "लंबे संपर्क से साँस की बीमारी। बाहर व्यायाम न करें; बाहर N95 पहनें।",
    severe: "स्वस्थ लोगों पर भी असर। घर में रहें, खिड़कियाँ बंद रखें, हो सके तो प्यूरीफ़ायर चलाएँ।",
  },
  pollutantsTitle: "अभी के प्रदूषक",
  next24h: "अगले 24 घंटे · PM2.5",
  now: "अभी",
  weatherLine: (temp, compass, speed) =>
    [temp !== null ? `${temp}°C` : null, compass && speed !== null ? `हवा ${compass} से, ${speed} km/h` : null]
      .filter(Boolean)
      .join(" · "),
  nearestStation: "सबसे पास का CPCB स्टेशन",
  stationLine: (km, aqi, t) => `${km} किमी दूर · सूचकांक ${aqi ?? "—"}${t ? ` · ${t} IST` : ""}`,
  firesTitle: "सैटेलाइट आग, पिछले 48 घंटे",
  firesLine: (near, upwind) => `50 किमी के भीतर ${near} · हवा की दिशा में 400 किमी तक ${upwind}`,
  firesUpwindHint: "हवा की दिशा वाली आग का धुआँ यहाँ आ सकता है।",
  insightTitle: "हवा ऐसी क्यों है?",
  insightLoading: "ख़बरें, आग और हवा पढ़ रहे हैं…",
  insightUnavailable: "अभी कोई व्याख्या नहीं।",
  kidTitle: "क्या बच्चे की तरह समझा सकते हो?",
  kidLangNote: "यह हिस्सा हमेशा आसान अंग्रेज़ी में है।",
  insightConfidence: { low: "कम भरोसा", medium: "मध्यम भरोसा", high: "ज़्यादा भरोसा" },
  newsTitle: (area) => `ख़बरों में · ${area}`,
  newsEmpty: "इस इलाके की हवा से जुड़ी कोई ताज़ा ख़बर नहीं।",
  newsMissing: "ख़बरों के लिए SerpApi की चाबी चाहिए।",
  newsNearest: (area) => `${area} की कोई ताज़ा ख़बर नहीं, इसलिए सबसे पास का शहर दिखा रहे हैं।`,
  newsFailed: {
    bad_key: "ख़बरों की सेवा ने हमारी चाबी अस्वीकार की।",
    out_of_searches: "ख़बरों की सेवा की इस महीने की खोजें ख़त्म हो गईं।",
    failed: "अभी ख़बरें नहीं आ सकीं।",
  },
  agoMinutes: (n) => `${n} मिनट पहले`,
  agoHours: (n) => `${n} घंटे पहले`,
  agoDays: (n) => `${n} दिन पहले`,
  tabs: { overview: "सारांश", city: "शहर", news: "ख़बरें", insight: "AI रिपोर्ट", reports: "रिपोर्ट" },
  expand: "पैनल चौड़ा करें",
  collapse: "पैनल छोटा करें",
  seeAll: "सब देखें",
  checksTitle: "हमने क्या जाँचा",
  checkerSaw: "जाँच में क्या दिखा",
  checkLabel: {
    quality: "फ़ोटो की गुणवत्ता",
    outdoor: "बाहर का दृश्य",
    authentic: "असली फ़ोटो",
    claim_match: "बताई गई बात से मेल",
    smoke_visible: "धुआँ या आग दिखी",
    place: "पिन वाली जगह से मेल",
    exif: "फ़ोटो की लोकेशन",
    satellite_fire: "पास में सैटेलाइट आग",
  },
  checkValue: (key, status, value) => {
    switch (key) {
      case "quality":
        return ({ good: "साफ़ और स्पष्ट", blurry: "धुंधली", dark: "बहुत अँधेरी", too_close: "बहुत पास से", obstructed: "नज़ारा ढका हुआ" } as Record<string, string>)[String(value)] ?? "";
      case "outdoor":
        return status === "pass" ? "हाँ" : "अंदर की लगती है";
      case "authentic":
        return status === "pass" ? "कैमरे की असली फ़ोटो लगती है" : "स्क्रीनशॉट या डाउनलोड की हुई लगती है";
      case "claim_match":
        return `${value ?? 0}% मेल`;
      case "smoke_visible":
        return status === "pass" ? "हाँ" : "साफ़ नहीं दिखा";
      case "place":
        return status === "pass" ? (value ? `संकेत: ${value}` : "कुछ विरोधी नहीं") : String(value || "कोई और जगह लगती है");
      case "exif":
        return status === "info" ? "फ़ोटो में GPS नहीं (कोई बात नहीं)" : `पिन से ${value} किमी`;
      case "satellite_fire":
        return status === "pass" ? `NASA ने ${value} किमी पर आग देखी` : "15 किमी में कोई सैटेलाइट आग नहीं";
    }
  },
  visibleLabel: {
    smoke: "धुआँ",
    dust: "धूल",
    haze: "धुंध",
    open_burning: "खुले में जलाना",
    construction: "निर्माण",
    traffic: "ट्रैफ़िक",
    none: "कुछ ख़ास नहीं",
    unclear: "साफ़ नहीं",
  },
  resultPublished: "रिपोर्ट प्रकाशित हुई",
  resultRejected: "रिपोर्ट प्रकाशित नहीं हुई",
  cityTitle: (city) => `${city} · CPCB स्टेशन`,
  cityNoStations: "इस जगह से 60 किमी के भीतर कोई CPCB स्टेशन नहीं।",
  cityAvg: "शहर का औसत",
  cityWorst: "सबसे ज़्यादा",
  cityBest: "सबसे कम",
  cityStations: (n, reporting) => `${n} में से ${reporting} स्टेशन रिपोर्ट कर रहे हैं`,
  cityCategories: "श्रेणी के अनुसार स्टेशन",
  cityDominant: "स्टेशनों पर मुख्य प्रदूषक",
  cityStationList: "सभी स्टेशन",
  cityIndexNote: "CPCB का प्रकाशित सूचकांक: हर स्टेशन पर सबसे ऊँचा प्रदूषक उप-सूचकांक।",
  cityFires: "सैटेलाइट आग, पिछले 48 घंटे",
  firesWithin: (km) => `${km} किमी के भीतर`,
  firesUpwindLabel: "हवा की दिशा में, 400 किमी",
  cityReports: "15 किमी के भीतर जाँची गई नागरिक रिपोर्ट",
  reportsLast7: "पिछले 7 दिन",
  reportsAll: "कुल",
  insightEvidence: "Gemini ने क्या देखा",
  evReading: "माप",
  evWind: "हवा",
  evTemp: "तापमान",
  evFires: "आग (48 घंटे)",
  evHeadlines: "ख़बरें",
  evBasis: (b) => `${b} पर मापा गया, पूरे दिल्ली NCR के लिए एक`,
  evFiresValue: (near, up) => `50 किमी में ${near} · हवा की दिशा में ${up}`,
  causesTitle: "संभावित कारण",
  citedTitle: "जिन ख़बरों का हवाला दिया",
  insightMeta: (model, t) => `${model} ने ${t} IST पर लिखा`,
  insightDisclaimer: "ऊपर के सबूतों का AI सारांश। यह ग़लत हो सकता है, और यह संख्या को कभी नहीं बदलता।",
  trendTitle: "PM2.5 का रुझान जो उसने देखा",
  feedTitle: "10 किमी के भीतर रिपोर्ट · पिछले 30 दिन",
  feedNone: "पिछले 30 दिनों में यहाँ कोई प्रकाशित रिपोर्ट नहीं।",
  feedPrivacy: "फ़ोटो और नोट निजी रहते हैं। आप देखते हैं कि क्या बताया गया, कब, और जाँच में क्या दिखा।",
  reportedAs: (claim) => `बताया गया: ${claim}`,
  confidenceShort: (n) => `${n}/100`,
  kmAway: (km) => `${km} किमी दूर`,
  compass: { n: "उत्तर", ne: "उत्तर-पूर्व", e: "पूर्व", se: "दक्षिण-पूर्व", s: "दक्षिण", sw: "दक्षिण-पश्चिम", w: "पश्चिम", nw: "उत्तर-पश्चिम" },
  ctxReportsFire: (n, km, dir, h, compass, speed) =>
    `5 किमी के भीतर ${n} जाँची गई रिपोर्ट। ${h} घंटे पहले यहाँ से ${km} किमी ${dir} में एक सैटेलाइट हॉटस्पॉट था। हवा ${compass} से ${speed} km/h पर है, इसलिए पास का धुआँ यहाँ आ सकता है।`,
  ctxReports: (n, compass, speed) =>
    `5 किमी के भीतर ${n} जाँची गई रिपोर्ट। हवा ${compass} से ${speed} km/h पर है।`,
  ctxReportsNoWind: (n) => `5 किमी के भीतर ${n} जाँची गई रिपोर्ट।`,
  ctxFire: (km, h) =>
    `5 किमी के भीतर कोई जाँची गई रिपोर्ट नहीं। ${h} घंटे पहले ${km} किमी दूर एक सैटेलाइट हॉटस्पॉट था।`,
  ctxNothing: "5 किमी के भीतर कोई जाँची गई रिपोर्ट नहीं। ऊपर की संख्या इस जगह का प्रति घंटा मान है, सड़क का सेंसर नहीं।",
  aboutTitle: "प्रोजेक्ट वायुचक्र के बारे में",
  aboutIntro:
    "प्रोजेक्ट वायुचक्र दिल्ली NCR और आस-पास के उत्तर भारत का लाइव हवा का नक्शा है। किसी भी जगह पर टैप करें: वहाँ की प्रति घंटा हवा, पास के CPCB स्टेशन, हवा की दिशा वाली सैटेलाइट आग, स्थानीय प्रदूषण की ख़बरें, और Gemini की पढ़ाई कि हवा ऐसी क्यों लग रही है। लोग फ़ोटो भी भेज सकते हैं — वह सिर्फ़ अपलोड नहीं होती, जाँची जाती है।",
  aboutDisclaimer:
    "बड़ी संख्या प्रति घंटा PM2.5 है, भारत AQI पैमाने पर — CPCB का आधिकारिक 24 घंटे का सूचकांक नहीं। नागरिकों की फ़ोटो Gemini जाँचता है; ये आधिकारिक माप नहीं हैं। जहाँ परत मॉडल है, नक्शा वह कहता है।",
  aboutMapTitle: "नक्शा",
  aboutMap: [
    "डिफ़ॉल्ट सैटेलाइट तस्वीर (Esri), या हल्का स्ट्रीट मैप। AQI हीटमैप, CPCB स्टेशन, सैटेलाइट आग और नागरिक रिपोर्ट ऑन-ऑफ किए जा सकते हैं।",
    "रंगीन हीटमैप Google Air Quality टाइलें हैं (US AQI रंग), जब Google की चाबी लगी हो। नहीं तो NCR के लिए मोटा CAMS मॉडल ग्रिड, भारत AQI पैमाने पर।",
    "स्टेशन बिन्दु data.gov.in से CPCB का अपना प्रकाशित सूचकांक हैं — साइट पर एकमात्र आधिकारिक मापे गए आँकड़े, लगभग 600। होवर पर माप; क्लिक से वह जगह चुनें।",
    "चमकते बिन्दु NASA FIRMS VIIRS की आग हैं, पिछले 48 घंटे, पंजाब, हरियाणा, दिल्ली और पश्चिमी उत्तर प्रदेश में। कार्ड 50 किमी के भीतर और हवा की दिशा में 400 किमी तक आग गिनता है, क्योंकि धुआँ चलता है।",
  ],
  aboutLiveTitle: "एक जगह पर क्या दिखता है",
  aboutLive: [
    "हेडर श्रेणी के रंग में है: स्वास्थ्य सलाह, तापमान और हवा, छह प्रदूषक (PM2.5, PM10, NO₂, O₃, CO, SO₂), और अगले 24 घंटे का PM2.5 चार्ट।",
    "शहर टैब: उस शहर (या 25 किमी) के CPCB स्टेशन, औसत, सबसे ज़्यादा और सबसे कम, मुख्य प्रदूषक, आग और रिपोर्ट की गिनती।",
    "ख़बर टैब: SerpApi से Google News — प्रदूषण, AQI, स्मॉग, आग। छोटी जगह पर ख़बर न हो तो सबसे पास का शहर।",
    "ग्रिड साथ-साथ देखने के लिए पैनल चौड़ा करें। सब एक ही पेज पर रहता है।",
  ],
  aboutAiTitle: "Gemini क्या करता है",
  aboutAi: [
    "“हवा ऐसी क्यों है?” सिर्फ़ उसी सबूत का Gemini सारांश है जो हमारे पास पहले से है: माप, 24 घंटे का रुझान, हवा, आग की गिनती और नंबर लगी ख़बरें। संभावित कारण बताता है और ख़बरों का नंबर से हवाला देता है। AQI की संख्या वह नहीं बदलता।",
    "“क्या बच्चे की तरह समझा सकते हो?” वही सबूत आसान अंग्रेज़ी में, जैसे आठ साल के बच्चे से बात हो। कठिन शब्द नहीं, बनाई हुई आग नहीं।",
    "फ़ोटो रिपोर्ट एक लाइव मल्टीमॉडल Gemini कॉल है। हम फ़ोटो के साथ आपका दावा, पिन, कैप्चर समय, EXIF GPS, पास का AQI, हवा और पास की सैटेलाइट आग भेजते हैं। ख़बरें केवल पृष्ठभूमि हैं; Gemini को फ़ोटो पर फ़ैसला करने को कहा जाता है, ख़बर पर नहीं।",
    "Gemini बताता है फ़ोटो में क्या है, गुणवत्ता, संगति और विरोध। सबूत स्कोर वायुचक्र खुद गिनता है: 30% फ़ोटो गुणवत्ता, 25% दृश्य घटना, 20% जगह/समय, 15% सैटेलाइट या सेंसर, 10% रिपोर्ट की संगति। यह प्रतिशत Gemini नहीं बनाता।",
    "60 से कम पर वह साफ़ कहता है कि नई फ़ोटो कैसे लें — पास से, निशान के साथ, अँधेरी न हो — तीन कोशिश तक। अंतिम स्कोर सबसे अच्छी फ़ोटो + सहमत फ़ोटो का बोनस − विरोध की कटौती।",
    "फ़ोटो स्वीकार होने पर Gemini अधिकारियों के लिए छोटा घटना संक्षेप लिखता है: शायद क्या हुआ, कहाँ, सबूत, आस-पास के इलाके, सुझाया कदम, और क्या अधूरा है। रिपोर्ट टैब पर दूसरों को यही कहानी दिखती है, फ़ोटो नहीं।",
  ],
  howTitle: "यह संख्या कैसे बनती है",
  howBody: [
    "हम उस जगह का ताज़ा प्रति घंटा PM2.5 Google Air Quality से लेते हैं। अगर Google के पास PM2.5 नहीं है, तो Open-Meteo के ज़रिए CAMS वैश्विक मॉडल लेते हैं, जो लगभग 45 किमी मोटा है। संख्या के नीचे हमेशा स्रोत लिखा होता है।",
    "इस प्रति घंटा मान को PM2.5 के CPCB 2014 भारत AQI ब्रेकपॉइंट पर रखते हैं। CPCB का आधिकारिक सूचकांक 24 घंटे का औसत और स्टेशन पर सबसे ख़राब प्रदूषक लेता है, इसलिए यह आधिकारिक CPCB AQI नहीं है — यह जल्दी बदलता है और ऊँचा या नीचा हो सकता है।",
    "अगर उस जगह के लिए उसी दिन का LightGBM स्थानिक अनुमान है, तो वह अलग पंक्ति में दिखता है। यह पुनर्निर्माण है, पूर्वानुमान नहीं। 24 घंटे की पट्टियाँ उसी स्रोत का प्रति घंटा पूर्वानुमान हैं, उसी तरह बदला हुआ।",
  ],
  sourcesTitle: "डेटा स्रोत",
  sources: [
    "Google Air Quality API — वर्तमान और प्रति घंटा पूर्वानुमान PM2.5 और अन्य प्रदूषक",
    "Google Air Quality हीटमैप टाइलें — रंगीन AQI परत (US AQI रंग)",
    "CAMS वैश्विक पूर्वानुमान, Open-Meteo — वैकल्पिक PM2.5",
    "Open-Meteo Forecast API — हवा और तापमान",
    "CPCB रियल-टाइम स्टेशन सूचकांक, data.gov.in — स्टेशन चिह्न और शहर टैब",
    "NASA FIRMS, VIIRS NOAA-20 (NOAA-21 पुनः) — पंजाब, हरियाणा, दिल्ली और पश्चिमी UP की सैटेलाइट आग",
    "SerpApi Google News — स्थानीय प्रदूषण, AQI, स्मॉग और आग की ख़बरें",
    "Gemini — फ़ोटो जाँच, “हवा ऐसी क्यों है?”, बच्चे जैसी व्याख्या, और घटना संक्षेप",
    "Google Geocoding, फिर OpenStreetMap Nominatim — जगह के नाम",
    "Imagery © Esri, Maxar, Earthstar Geographics · Map © OpenStreetMap contributors © CARTO",
  ],
  photosTitle: "फ़ोटो रिपोर्ट",
  photosBody:
    "हर रिपोर्ट को फ़ोटो के तीन मौके मिलते हैं। हमारी तरफ़ की नाकामी (कोटा, मॉडल नहीं मिला) मौका नहीं खाती। नक्शे पर केवल जाँची गई और संभावित रिपोर्ट दिखती हैं। फ़ोटो और नोट निजी रहते हैं; सार्वजनिक सूची में क्या बताया गया, कब, कितनी दूर, जाँच में क्या दिखा, और संक्षेप दिखता है।",
  aboutPrivacyTitle: "चाबियाँ और गोपनीयता",
  aboutPrivacy:
    "Gemini, Google, FIRMS, data.gov.in, SerpApi और डेटाबेस की सेवा-भूमिका सर्वर पर रहती हैं। ब्राउज़र को ये चाबियाँ नहीं मिलतीं। रिपोर्ट की पढ़ाई-लिखाई Next.js रूटों से सेवा-भूमिका के साथ होती है; प्रयासों या Gemini JSON के लिए कोई खुली डेटाबेस नीति नहीं है।",
};

export const COPY: Record<Lang, Copy> = { en, hi };

export const CATEGORY_LABEL: Record<Lang, Record<CategoryKey, string>> = {
  en: { good: "Good", satisfactory: "Satisfactory", moderate: "Moderate", poor: "Poor", very_poor: "Very poor", severe: "Severe" },
  hi: { good: "अच्छा", satisfactory: "संतोषजनक", moderate: "मध्यम", poor: "ख़राब", very_poor: "बहुत ख़राब", severe: "गंभीर" },
};

export function hardFailMessage(lang: Lang, reason: HardFailReason, km?: number): string {
  return COPY[lang].hardFail[reason].replace("{km}", km === undefined ? "" : km < 10 ? km.toFixed(1) : String(Math.round(km)));
}
